import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],  // Correctly passing subsets as an array
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],  // Correctly passing subsets as an array
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetBrainsMono",
});
export const metadata = {
  title: "Portfolio - Farhee A. Ahmad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.variable} antialiased`}>
        <Header/>
        <StairTransition/>
        <PageTransition/>
        {children}
        
      </body>
    </html>
  );
}
